sonar.host.url=http://18.215.255.49:9000
sonar.projectKey=Pipeline:project
sonar.projectName=Pipeline-project
sonar.projectVersion=1.0
sonar.sources=./
sonar.java.binaries=.
sonar.sourceEncoding=UTF-8
sonar.login=sqp_276f0ddf4874f6f9803b0a962f1e001eb9f510a9
